FROM squareslab/ardubugs:base
ARG rev_fix
RUN cd /opt/ardupilot \
 && git reset --hard "${rev_fix}~1" \
 && git submodule update --init --recursive \
 && ./configure \
 && ./builder all \
 && sudo chown -R docker /opt
