FROM squareslab/ardubugs:rover

ARG rev_fix

# rollback to the version of the source code immediately prior to the fix revision
RUN cd /experiment/source && \
    make clean && \
    git clean -fd && \
    git checkout "${rev_fix}~1"
