FROM squareslab/ardubugs:base
ARG rev_fix
RUN cd /opt/ardupilot \
 && git clean -fd \
 && git checkout "${rev_fix}~1" \
 && git submodule update --init --recursive \
 && ./configure \
 && bear ./builder all \
 && sudo chown -R docker /opt
