FROM squareslab/ardubugs:base
ARG rev_fix
RUN cd /opt/ardupilot \
 && git clean -fd \
 && git checkout "${rev_fix}~1" \
 && git submodule update --init --recursive \
 && ./waf configure --no-submodule-update \
 && bear ./waf build -j8 \
 && sudo chown -R docker /opt
